### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AtomicError** [dheison0/telegram-downloader#2]
root@sound-nest:~/bot# python3 -m bot
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/root/bot/bot/__init__.py", line 14, in <module>
    ADMINS = getenv('@Iamhere002').split()
AttributeError: 'NoneType' object has no attribute 'split'

how to fix this?

**Comment by AtomicError** [comment]
i do wrong 
The problem is not yours, I did something wrong
